# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidgetItem
import signals
import sys
import images


class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.setEnabled(True)
        main_window.resize(1390, 800)
        main_window.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        main_window.setStyleSheet(
            "background-image: url(:/images/images/back1.png);")
        self.memory_table = QtWidgets.QTableWidget(main_window)
        self.memory_table.setEnabled(True)
        self.memory_table.setGeometry(QtCore.QRect(850, 200, 211, 411))
        font = QtGui.QFont()
        font.setFamily("Mj_Fikrah Light")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.memory_table.setFont(font)
        self.memory_table.viewport().setProperty(
            "cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.memory_table.setStyleSheet("background:#afc5d0;\n"
                                        "border-radius: 15px;\n"
                                        "color: rgb(43, 43, 43);\n"
                                        "font: 8pt \"Mj_Fikrah Light\";\n"
                                        "")
        self.memory_table.setVerticalScrollBarPolicy(
            QtCore.Qt.ScrollBarAsNeeded)
        self.memory_table.setHorizontalScrollBarPolicy(
            QtCore.Qt.ScrollBarAlwaysOff)
        self.memory_table.setSizeAdjustPolicy(
            QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.memory_table.setEditTriggers(
            QtWidgets.QAbstractItemView.NoEditTriggers)
        self.memory_table.setTabKeyNavigation(False)
        self.memory_table.setProperty("showDropIndicator", False)
        self.memory_table.setDragDropOverwriteMode(False)
        self.memory_table.setVerticalScrollMode(
            QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.memory_table.setHorizontalScrollMode(
            QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.memory_table.setShowGrid(True)
        self.memory_table.setGridStyle(QtCore.Qt.DashDotLine)
        self.memory_table.setWordWrap(True)
        self.memory_table.setCornerButtonEnabled(True)
        self.memory_table.setRowCount(4096)
        self.memory_table.setColumnCount(3)
        self.memory_table.setObjectName("memory_table")
        item = QtWidgets.QTableWidgetItem()
        self.memory_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.memory_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.memory_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.memory_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.memory_table.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.memory_table.setItem(0, 2, item)
        self.memory_table.horizontalHeader().setVisible(True)
        self.memory_table.horizontalHeader().setCascadingSectionResizes(False)
        self.memory_table.horizontalHeader().setDefaultSectionSize(64)
        self.memory_table.horizontalHeader().setHighlightSections(True)
        self.memory_table.verticalHeader().setVisible(False)
        self.memory_table.verticalHeader().setDefaultSectionSize(30)
        self.memory_table.verticalHeader().setHighlightSections(False)
        self.memory_table.verticalHeader().setMinimumSectionSize(25)
        self.memory_table.verticalHeader().setStretchLastSection(False)
        self.coding_text = QtWidgets.QPlainTextEdit(main_window)
        self.coding_text.setGeometry(QtCore.QRect(290, 200, 201, 331))
        self.coding_text.viewport().setProperty(
            "cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.coding_text.setStyleSheet("background:#afc5d0;\n"
                                       "color: rgb(43, 43, 43);\n"
                                       "border-radius: 15px;\n"
                                       "padding: 9px;\n"
                                       "font: 9pt \"Mj_Fikrah Light\";\n"
                                       "\n"
                                       "")
        self.coding_text.setObjectName("coding_text")
        self.microoperation = QtWidgets.QLineEdit(main_window)
        self.microoperation.setGeometry(QtCore.QRect(540, 440, 261, 41))
        self.microoperation.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.microoperation.setStyleSheet("color: rgb(43, 43, 43);\n"
                                          "background:#afc5d0;\n"
                                          "border-radius: 15px;\n"
                                          "padding: 9px;\n"
                                          "font: 8pt \"Mj_Fikrah Light\";\n"
                                          "")
        self.microoperation.setReadOnly(True)
        self.microoperation.setObjectName("microoperation")
        self.console = QtWidgets.QPlainTextEdit(main_window)
        self.console.setGeometry(QtCore.QRect(540, 520, 261, 91))
        self.console.viewport().setProperty(
            "cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.console.setMouseTracking(True)
        self.console.setTabletTracking(False)
        self.console.setStyleSheet("color: rgb(43, 43, 43);\n"
                                   "background:#afc5d0;\n"
                                   "border-radius: 15px;\n"
                                   "padding: 7px;\n"
                                   "padding-top: 2px;\n"
                                   "font: 9pt \"Mj_Fikrah Light\";")
        self.console.setReadOnly(True)
        self.console.setObjectName("console")
        self.coding_label = QtWidgets.QLabel(main_window)
        self.coding_label.setGeometry(QtCore.QRect(300, 180, 91, 16))
        self.coding_label.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.coding_label.setStyleSheet("background: #0000ffff;\n"
                                        "color: #afc5d0;\n"
                                        "font: 10pt \"MS Serif\";\n"
                                        "font: 75 10pt \"MS Shell Dlg 2\";")
        self.coding_label.setObjectName("coding_label")
        self.input_label = QtWidgets.QLabel(main_window)
        self.input_label.setGeometry(QtCore.QRect(300, 540, 61, 31))
        self.input_label.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.input_label.setStyleSheet("background: #0000ffff;\n"
                                       "color: #afc5d0;\n"
                                       "font: 10pt \"MS Serif\";\n"
                                       "font: 75 10pt \"MS Shell Dlg 2\";")
        self.input_label.setObjectName("input_label")
        self.console_label = QtWidgets.QLabel(main_window)
        self.console_label.setGeometry(QtCore.QRect(550, 500, 81, 16))
        self.console_label.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.console_label.setStyleSheet("background: #0000ffff;\n"
                                         "color: #afc5d0;\n"
                                         "font: 10pt \"MS Serif\";\n"
                                         "font: 75 10pt \"MS Shell Dlg 2\";")
        self.console_label.setObjectName("console_label")
        self.microoperation_label = QtWidgets.QLabel(main_window)
        self.microoperation_label.setGeometry(QtCore.QRect(550, 420, 131, 16))
        self.microoperation_label.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.microoperation_label.setStyleSheet("background: #0000ffff;\n"
                                                "color: #afc5d0;\n"
                                                "font: 10pt \"MS Serif\";\n"
                                                "font: 75 10pt \"MS Shell Dlg 2\";")
        self.microoperation_label.setObjectName("microoperation_label")
        self.SC_value_label = QtWidgets.QLabel(main_window)
        self.SC_value_label.setGeometry(QtCore.QRect(550, 210, 41, 31))
        self.SC_value_label.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SC_value_label.setStyleSheet("background: #0000ffff;\n"
                                          "border-radius: 0px;\n"
                                          "background-image: url(:/images/images/frame.png);\n"
                                          "background-repeat: no-repeat;\n"
                                          "color: #afc5d0;\n"
                                          "font: 75 8pt \"MS Shell Dlg 2\";")
        self.SC_value_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.SC_value_label.setLineWidth(0)
        self.SC_value_label.setScaledContents(False)
        self.SC_value_label.setAlignment(QtCore.Qt.AlignCenter)
        self.SC_value_label.setIndent(0)
        self.SC_value_label.setObjectName("SC_value_label")
        self.SC_label = QtWidgets.QLabel(main_window)
        self.SC_label.setGeometry(QtCore.QRect(560, 190, 21, 16))
        self.SC_label.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SC_label.setStyleSheet("background: #0000ffff;\n"
                                    "color: #afc5d0;\n"
                                    "font: 10pt \"MS Serif\";\n"
                                    "font: 75 8pt \"MS Shell Dlg 2\";\n"
                                    "qproperty-alignment: AlignCenter;\n"
                                    "\n"
                                    "")
        self.SC_label.setObjectName("SC_label")
        self.PC_value_label = QtWidgets.QLabel(main_window)
        self.PC_value_label.setGeometry(QtCore.QRect(600, 210, 41, 31))
        self.PC_value_label.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PC_value_label.setStyleSheet("background: #0000ffff;\n"
                                          "border-radius: 0px;\n"
                                          "background-image: url(:/images/images/frame.png);\n"
                                          "background-repeat: no-repeat;\n"
                                          "color: #afc5d0;\n"
                                          "font: 75 8pt \"MS Shell Dlg 2\";")
        self.PC_value_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.PC_value_label.setAlignment(QtCore.Qt.AlignCenter)
        self.PC_value_label.setObjectName("PC_value_label")
        self.PC_label = QtWidgets.QLabel(main_window)
        self.PC_label.setGeometry(QtCore.QRect(610, 190, 21, 20))
        self.PC_label.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PC_label.setStyleSheet("background: #0000ffff;\n"
                                    "color: #afc5d0;\n"
                                    "qproperty-alignment: AlignCenter;\n"
                                    "\n"
                                    "font: 10pt \"MS Serif\";\n"
                                    "font: 75 8pt \"MS Shell Dlg 2\";")
        self.PC_label.setObjectName("PC_label")
        self.AR_value_label = QtWidgets.QLabel(main_window)
        self.AR_value_label.setGeometry(QtCore.QRect(650, 210, 41, 31))
        self.AR_value_label.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.AR_value_label.setStyleSheet("background: #0000ffff;\n"
                                          "border-radius: 0px;\n"
                                          "background-image: url(:/images/images/frame.png);\n"
                                          "background-repeat: no-repeat;\n"
                                          "color: #afc5d0;\n"
                                          "font: 75 8pt \"MS Shell Dlg 2\";")
        self.AR_value_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.AR_value_label.setAlignment(QtCore.Qt.AlignCenter)
        self.AR_value_label.setObjectName("AR_value_label")
        self.AR_label = QtWidgets.QLabel(main_window)
        self.AR_label.setGeometry(QtCore.QRect(660, 190, 21, 20))
        self.AR_label.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.AR_label.setStyleSheet("background: #0000ffff;\n"
                                    "color: #afc5d0;\n"
                                    "font: 10pt \"MS Serif\";\n"
                                    "font: 75 8pt \"MS Shell Dlg 2\";\n"
                                    "\n"
                                    "qproperty-alignment: AlignCenter;\n"
                                    "")
        self.AR_label.setObjectName("AR_label")
        self.IR_value_label = QtWidgets.QLabel(main_window)
        self.IR_value_label.setGeometry(QtCore.QRect(700, 210, 41, 31))
        self.IR_value_label.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.IR_value_label.setStyleSheet("background: #0000ffff;\n"
                                          "border-radius: 0px;\n"
                                          "background-image: url(:/images/images/frame.png);\n"
                                          "background-repeat: no-repeat;\n"
                                          "color: #afc5d0;\n"
                                          "font: 75 8pt \"MS Shell Dlg 2\";")
        self.IR_value_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.IR_value_label.setAlignment(QtCore.Qt.AlignCenter)
        self.IR_value_label.setObjectName("IR_value_label")
        self.IR_label = QtWidgets.QLabel(main_window)
        self.IR_label.setGeometry(QtCore.QRect(710, 190, 21, 20))
        self.IR_label.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.IR_label.setStyleSheet("background: #0000ffff;\n"
                                    "color: #afc5d0;\n"
                                    "font: 10pt \"MS Serif\";\n"
                                    "font: 75 8pt \"MS Shell Dlg 2\";\n"
                                    "qproperty-alignment: AlignCenter;\n"
                                    "")
        self.IR_label.setObjectName("IR_label")
        self.DR_value_label = QtWidgets.QLabel(main_window)
        self.DR_value_label.setGeometry(QtCore.QRect(750, 210, 41, 31))
        self.DR_value_label.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.DR_value_label.setStyleSheet("background: #0000ffff;\n"
                                          "border-radius: 0px;\n"
                                          "background-image: url(:/images/images/frame.png);\n"
                                          "background-repeat: no-repeat;\n"
                                          "color: #afc5d0;\n"
                                          "font: 75 8pt \"MS Shell Dlg 2\";")
        self.DR_value_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.DR_value_label.setAlignment(QtCore.Qt.AlignCenter)
        self.DR_value_label.setObjectName("DR_value_label")
        self.DR_label = QtWidgets.QLabel(main_window)
        self.DR_label.setGeometry(QtCore.QRect(760, 190, 21, 20))
        self.DR_label.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.DR_label.setStyleSheet("background: #0000ffff;\n"
                                    "color: #afc5d0;\n"
                                    "font: 10pt \"MS Serif\";\n"
                                    "font: 75 8pt \"MS Shell Dlg 2\";\n"
                                    "qproperty-alignment: AlignCenter;\n"
                                    "")
        self.DR_label.setObjectName("DR_label")
        self.AC_value_label = QtWidgets.QLabel(main_window)
        self.AC_value_label.setGeometry(QtCore.QRect(550, 270, 41, 31))
        self.AC_value_label.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.AC_value_label.setStyleSheet("background: #0000ffff;\n"
                                          "border-radius: 0px;\n"
                                          "background-image: url(:/images/images/frame.png);\n"
                                          "background-repeat: no-repeat;\n"
                                          "color: #afc5d0;\n"
                                          "font: 75 8pt \"MS Shell Dlg 2\";")
        self.AC_value_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.AC_value_label.setAlignment(QtCore.Qt.AlignCenter)
        self.AC_value_label.setObjectName("AC_value_label")
        self.AC_label = QtWidgets.QLabel(main_window)
        self.AC_label.setGeometry(QtCore.QRect(560, 250, 21, 16))
        self.AC_label.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.AC_label.setStyleSheet("background: #0000ffff;\n"
                                    "color: #afc5d0;\n"
                                    "font: 10pt \"MS Serif\";\n"
                                    "font: 75 8pt \"MS Shell Dlg 2\";\n"
                                    "qproperty-alignment: AlignCenter;\n"
                                    "\n"
                                    "")
        self.AC_label.setObjectName("AC_label")
        self.TR_label = QtWidgets.QLabel(main_window)
        self.TR_label.setGeometry(QtCore.QRect(610, 250, 21, 20))
        self.TR_label.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.TR_label.setStyleSheet("background: #0000ffff;\n"
                                    "color: #afc5d0;\n"
                                    "font: 10pt \"MS Serif\";\n"
                                    "font: 75 8pt \"MS Shell Dlg 2\";\n"
                                    "\n"
                                    "qproperty-alignment: AlignCenter;\n"
                                    "")
        self.TR_label.setObjectName("TR_label")
        self.INPR_label = QtWidgets.QLabel(main_window)
        self.INPR_label.setGeometry(QtCore.QRect(648, 250, 41, 20))
        self.INPR_label.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.INPR_label.setStyleSheet("background: #0000ffff;\n"
                                      "color: #afc5d0;\n"
                                      "font: 10pt \"MS Serif\";\n"
                                      "font: 75 8pt \"MS Shell Dlg 2\";\n"
                                      "\n"
                                      "qproperty-alignment: AlignCenter;\n"
                                      "")
        self.INPR_label.setObjectName("INPR_label")
        self.OUTR_label = QtWidgets.QLabel(main_window)
        self.OUTR_label.setGeometry(QtCore.QRect(698, 250, 41, 20))
        self.OUTR_label.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.OUTR_label.setStyleSheet("background: #0000ffff;\n"
                                      "color: #afc5d0;\n"
                                      "font: 10pt \"MS Serif\";\n"
                                      "font: 75 8pt \"MS Shell Dlg 2\";\n"
                                      "\n"
                                      "qproperty-alignment: AlignCenter;\n"
                                      "")
        self.OUTR_label.setObjectName("OUTR_label")
        self.I_label = QtWidgets.QLabel(main_window)
        self.I_label.setGeometry(QtCore.QRect(570, 320, 16, 20))
        self.I_label.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.I_label.setStyleSheet("background: #0000ffff;\n"
                                   "color: #afc5d0;\n"
                                   "font: 10pt \"MS Serif\";\n"
                                   "font: 75 8pt \"MS Shell Dlg 2\";\n"
                                   "\n"
                                   "qproperty-alignment: AlignCenter;\n"
                                   "")
        self.I_label.setObjectName("I_label")
        self.S_label = QtWidgets.QLabel(main_window)
        self.S_label.setGeometry(QtCore.QRect(630, 320, 16, 20))
        self.S_label.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.S_label.setStyleSheet("background: #0000ffff;\n"
                                   "color: #afc5d0;\n"
                                   "font: 10pt \"MS Serif\";\n"
                                   "font: 75 8pt \"MS Shell Dlg 2\";\n"
                                   "\n"
                                   "qproperty-alignment: AlignCenter;\n"
                                   "")
        self.S_label.setObjectName("S_label")
        self.E_label = QtWidgets.QLabel(main_window)
        self.E_label.setGeometry(QtCore.QRect(690, 320, 16, 20))
        self.E_label.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.E_label.setStyleSheet("background: #0000ffff;\n"
                                   "color: #afc5d0;\n"
                                   "font: 10pt \"MS Serif\";\n"
                                   "font: 75 8pt \"MS Shell Dlg 2\";\n"
                                   "\n"
                                   "qproperty-alignment: AlignCenter;\n"
                                   "")
        self.E_label.setObjectName("E_label")
        self.R_label = QtWidgets.QLabel(main_window)
        self.R_label.setGeometry(QtCore.QRect(750, 320, 16, 20))
        self.R_label.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.R_label.setStyleSheet("background: #0000ffff;\n"
                                   "color: #afc5d0;\n"
                                   "font: 10pt \"MS Serif\";\n"
                                   "font: 75 8pt \"MS Shell Dlg 2\";\n"
                                   "\n"
                                   "qproperty-alignment: AlignCenter;\n"
                                   "")
        self.R_label.setObjectName("R_label")
        self.IEN_label = QtWidgets.QLabel(main_window)
        self.IEN_label.setEnabled(False)
        self.IEN_label.setGeometry(QtCore.QRect(598, 360, 21, 20))
        self.IEN_label.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.IEN_label.setStyleSheet("background: #0000ffff;\n"
                                     "color: #afc5d0;\n"
                                     "font: 10pt \"MS Serif\";\n"
                                     "font: 75 8pt \"MS Shell Dlg 2\";\n"
                                     "\n"
                                     "qproperty-alignment: AlignCenter;\n"
                                     "")
        self.IEN_label.setObjectName("IEN_label")
        self.FGI_label = QtWidgets.QLabel(main_window)
        self.FGI_label.setEnabled(False)
        self.FGI_label.setGeometry(QtCore.QRect(658, 360, 21, 20))
        self.FGI_label.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.FGI_label.setStyleSheet("background: #0000ffff;\n"
                                     "color: #afc5d0;\n"
                                     "font: 10pt \"MS Serif\";\n"
                                     "font: 75 8pt \"MS Shell Dlg 2\";\n"
                                     "\n"
                                     "qproperty-alignment: AlignCenter;\n"
                                     "")
        self.FGI_label.setObjectName("FGI_label")
        self.FGO_label = QtWidgets.QLabel(main_window)
        self.FGO_label.setEnabled(False)
        self.FGO_label.setGeometry(QtCore.QRect(710, 360, 41, 20))
        self.FGO_label.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.FGO_label.setStyleSheet("background: #0000ffff;\n"
                                     "color: #afc5d0;\n"
                                     "font: 10pt \"MS Serif\";\n"
                                     "font: 75 8pt \"MS Shell Dlg 2\";\n"
                                     "\n"
                                     "qproperty-alignment: AlignCenter;\n"
                                     "")
        self.FGO_label.setObjectName("FGO_label")
        self.TR_value_label = QtWidgets.QLabel(main_window)
        self.TR_value_label.setGeometry(QtCore.QRect(600, 270, 41, 31))
        self.TR_value_label.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.TR_value_label.setStyleSheet("background: #0000ffff;\n"
                                          "border-radius: 0px;\n"
                                          "background-image: url(:/images/images/frame.png);\n"
                                          "background-repeat: no-repeat;\n"
                                          "color: #afc5d0;\n"
                                          "font: 75 8pt \"MS Shell Dlg 2\";")
        self.TR_value_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.TR_value_label.setAlignment(QtCore.Qt.AlignCenter)
        self.TR_value_label.setObjectName("TR_value_label")
        self.INPR_value_label = QtWidgets.QLabel(main_window)
        self.INPR_value_label.setGeometry(QtCore.QRect(650, 270, 41, 31))
        self.INPR_value_label.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.INPR_value_label.setStyleSheet("background: #0000ffff;\n"
                                            "border-radius: 0px;\n"
                                            "background-image: url(:/images/images/frame.png);\n"
                                            "background-repeat: no-repeat;\n"
                                            "color: #afc5d0;\n"
                                            "font: 75 8pt \"MS Shell Dlg 2\";")
        self.INPR_value_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.INPR_value_label.setAlignment(QtCore.Qt.AlignCenter)
        self.INPR_value_label.setObjectName("INPR_value_label")
        self.OUTR_value_label = QtWidgets.QLabel(main_window)
        self.OUTR_value_label.setGeometry(QtCore.QRect(700, 270, 41, 31))
        self.OUTR_value_label.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.OUTR_value_label.setStyleSheet("background: #0000ffff;\n"
                                            "border-radius: 0px;\n"
                                            "background-image: url(:/images/images/frame.png);\n"
                                            "background-repeat: no-repeat;\n"
                                            "color: #afc5d0;\n"
                                            "font: 75 8pt \"MS Shell Dlg 2\";")
        self.OUTR_value_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.OUTR_value_label.setAlignment(QtCore.Qt.AlignCenter)
        self.OUTR_value_label.setObjectName("OUTR_value_label")
        self.run_button = QtWidgets.QPushButton(main_window)
        self.run_button.setGeometry(QtCore.QRect(250, 385, 31, 31))
        self.run_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.run_button.setStyleSheet("background: #0000ffff;\n"
                                      "border-radius: 0px;\n"
                                      "background-image: url(:/images/images/run.png);\n"
                                      "background-repeat: no-repeat;\n"
                                      "")
        self.run_button.setText("")
        self.run_button.setObjectName("run_button")
        self.code_button = QtWidgets.QPushButton(main_window)
        self.code_button.setGeometry(QtCore.QRect(250, 490, 31, 31))
        self.code_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.code_button.setStyleSheet("background: #0000ffff;\n"
                                       "border-radius: 0px;\n"
                                       "background-image: url(:/images/images/code.png);\n"
                                       "background-repeat: no-repeat;")
        self.code_button.setText("")
        self.code_button.setObjectName("code_button")
        self.stop_button = QtWidgets.QPushButton(main_window)
        self.stop_button.setGeometry(QtCore.QRect(250, 455, 31, 31))
        self.stop_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.stop_button.setStyleSheet("background: #0000ffff;\n"
                                       "border-radius: 0px;\n"
                                       "background-image: url(:/images/images/stop.png);\n"
                                       "background-repeat: no-repeat;")
        self.stop_button.setText("")
        self.stop_button.setObjectName("stop_button")
        self.next_button = QtWidgets.QPushButton(main_window)
        self.next_button.setGeometry(QtCore.QRect(250, 420, 31, 31))
        self.next_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.next_button.setStyleSheet("background: #0000ffff;\n"
                                       "border-radius: 0px;\n"
                                       "background-image: url(:/images/images/next.png);\n"
                                       "background-repeat: no-repeat;")
        self.next_button.setText("")
        self.next_button.setObjectName("next_button")
        self.open_button = QtWidgets.QPushButton(main_window)
        self.open_button.setGeometry(QtCore.QRect(330, 110, 31, 31))
        self.open_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.open_button.setStyleSheet("background: #0000ffff;\n"
                                       "background-image: url(:/images/images/open.png);\n"
                                       "border-radius: 0px;\n"
                                       "background-repeat: no-repeat;")
        self.open_button.setText("")
        self.open_button.setObjectName("open_button")
        self.save_button = QtWidgets.QPushButton(main_window)
        self.save_button.setGeometry(QtCore.QRect(290, 105, 31, 41))
        self.save_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.save_button.setStyleSheet("border-radius: 0px;\n"
                                       "background-image: url(:/images/images/save.png);")
        self.save_button.setText("")
        self.save_button.setObjectName("save_button")
        self.line = QtWidgets.QFrame(main_window)
        self.line.setGeometry(QtCore.QRect(289, 150, 70, 3))
        self.line.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.line.setStyleSheet("background: #28aae2;")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.compile_button = QtWidgets.QPushButton(main_window)
        self.compile_button.setGeometry(QtCore.QRect(250, 350, 31, 31))
        self.compile_button.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.compile_button.setStyleSheet("background: #0000ffff;\n"
                                          "border-radius: 0px;\n"
                                          "background-repeat: no-repeat;\n"
                                          "background-image: url(:/images/images/hammer.png);")
        self.compile_button.setText("")
        self.compile_button.setObjectName("compile_button")
        self.goto_information = QtWidgets.QPushButton(main_window)
        self.goto_information.setGeometry(QtCore.QRect(1205, 605, 51, 51))
        self.goto_information.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.goto_information.setStyleSheet("background: #0000ffff;\n"
                                            "border-radius: 0px;\n"
                                            "background-repeat: no-repeat;\n"
                                            "background-image: url(:/images/images/team.png);")
        self.goto_information.setText("")
        self.goto_information.setObjectName("goto_information")
        self.INST_label = QtWidgets.QLabel(main_window)
        self.INST_label.setGeometry(QtCore.QRect(750, 250, 41, 20))
        self.INST_label.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.INST_label.setStyleSheet("background: #0000ffff;\n"
                                      "color: #afc5d0;\n"
                                      "font: 10pt \"MS Serif\";\n"
                                      "font: 75 8pt \"MS Shell Dlg 2\";\n"
                                      "\n"
                                      "qproperty-alignment: AlignCenter;\n"
                                      "")
        self.INST_label.setObjectName("INST_label")
        self.INST_value_label = QtWidgets.QLabel(main_window)
        self.INST_value_label.setGeometry(QtCore.QRect(750, 270, 41, 31))
        self.INST_value_label.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.INST_value_label.setStyleSheet("background: #0000ffff;\n"
                                            "border-radius: 0px;\n"
                                            "background-image: url(:/images/images/frame.png);\n"
                                            "background-repeat: no-repeat;\n"
                                            "color: #afc5d0;\n"
                                            "font: 75 8pt \"MS Shell Dlg 2\";")
        self.INST_value_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.INST_value_label.setAlignment(QtCore.Qt.AlignCenter)
        self.INST_value_label.setObjectName("INST_value_label")
        self.input = QtWidgets.QLineEdit(main_window)
        self.input.setGeometry(QtCore.QRect(290, 570, 201, 41))
        self.input.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.input.setStyleSheet("color: rgb(43, 43, 43);\n"
                                 "background:#afc5d0;\n"
                                 "border-radius: 15px;\n"
                                 "padding-left: 9px;\n"
                                 "font: 75 10pt \"Mj_Fikrah Light\";\n"
                                 "")
        self.input.setObjectName("input")
        self.I_value = QtWidgets.QLabel(main_window)
        self.I_value.setEnabled(False)
        self.I_value.setGeometry(QtCore.QRect(569, 340, 20, 20))
        self.I_value.setBaseSize(QtCore.QSize(30, 30))
        palette = QtGui.QPalette()
        self.I_value.setPalette(palette)
        self.I_value.setStyleSheet("background:none;")
        self.I_value.setText("")
        self.I_value.setPixmap(QtGui.QPixmap(":/images/images/green.png"))
        self.I_value.setScaledContents(True)
        self.I_value.setObjectName("I_value")
        self.FGO_value = QtWidgets.QLabel(main_window)
        self.FGO_value.setEnabled(False)
        self.FGO_value.setGeometry(QtCore.QRect(720, 380, 20, 20))
        self.FGO_value.setBaseSize(QtCore.QSize(30, 30))
        palette = QtGui.QPalette()
        self.FGO_value.setPalette(palette)
        self.FGO_value.setStyleSheet("background:none;")
        self.FGO_value.setText("")
        self.FGO_value.setPixmap(QtGui.QPixmap(":/images/images/green.png"))
        self.FGO_value.setScaledContents(True)
        self.FGO_value.setObjectName("FGO_value")
        self.FGI_value = QtWidgets.QLabel(main_window)
        self.FGI_value.setEnabled(False)
        self.FGI_value.setGeometry(QtCore.QRect(659, 380, 20, 20))
        self.FGI_value.setBaseSize(QtCore.QSize(30, 30))
        palette = QtGui.QPalette()
        self.FGI_value.setPalette(palette)
        self.FGI_value.setStyleSheet("background:none;")
        self.FGI_value.setText("")
        self.FGI_value.setPixmap(QtGui.QPixmap(":/images/images/green.png"))
        self.FGI_value.setScaledContents(True)
        self.FGI_value.setObjectName("FGI_value")
        self.IEN_value = QtWidgets.QLabel(main_window)
        self.IEN_value.setEnabled(False)
        self.IEN_value.setGeometry(QtCore.QRect(599, 380, 20, 20))
        self.IEN_value.setBaseSize(QtCore.QSize(30, 30))
        palette = QtGui.QPalette()
        self.IEN_value.setPalette(palette)
        self.IEN_value.setStyleSheet("background:none;")
        self.IEN_value.setText("")
        self.IEN_value.setPixmap(QtGui.QPixmap(":/images/images/green.png"))
        self.IEN_value.setScaledContents(True)
        self.IEN_value.setObjectName("IEN_value")
        self.R_value = QtWidgets.QLabel(main_window)
        self.R_value.setEnabled(False)
        self.R_value.setGeometry(QtCore.QRect(749, 340, 20, 20))
        self.R_value.setBaseSize(QtCore.QSize(30, 30))
        palette = QtGui.QPalette()
        self.R_value.setPalette(palette)
        self.R_value.setStyleSheet("background:none;")
        self.R_value.setText("")
        self.R_value.setPixmap(QtGui.QPixmap(":/images/images/green.png"))
        self.R_value.setScaledContents(True)
        self.R_value.setObjectName("R_value")
        self.E_value = QtWidgets.QLabel(main_window)
        self.E_value.setEnabled(False)
        self.E_value.setGeometry(QtCore.QRect(689, 340, 20, 20))
        self.E_value.setBaseSize(QtCore.QSize(30, 30))
        palette = QtGui.QPalette()
        self.E_value.setPalette(palette)
        self.E_value.setStyleSheet("background:none;")
        self.E_value.setText("")
        self.E_value.setPixmap(QtGui.QPixmap(":/images/images/green.png"))
        self.E_value.setScaledContents(True)
        self.E_value.setObjectName("E_value")
        self.S_value = QtWidgets.QLabel(main_window)
        self.S_value.setEnabled(False)
        self.S_value.setGeometry(QtCore.QRect(629, 340, 20, 20))
        self.S_value.setBaseSize(QtCore.QSize(30, 30))
        palette = QtGui.QPalette()
        self.S_value.setPalette(palette)
        self.S_value.setStyleSheet("background:none;")
        self.S_value.setText("")
        self.S_value.setPixmap(QtGui.QPixmap(":/images/images/green.png"))
        self.S_value.setScaledContents(True)
        self.S_value.setObjectName("S_value")

        for i in range(4096):
            item = QTableWidgetItem(str(hex(i))[2:].upper().zfill(3))
            item.setTextAlignment(4)
            self.memory_table.setItem(i, 1, item)
        signals.set_memory(self.memory_table)

        self.dialog = Info()

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "Mano Simulator"))
        item = self.memory_table.horizontalHeaderItem(0)
        item.setText(_translate("main_window", "Label"))
        item = self.memory_table.horizontalHeaderItem(1)
        item.setText(_translate("main_window", "Address"))
        item = self.memory_table.horizontalHeaderItem(2)
        item.setText(_translate("main_window", "Hex"))
        __sortingEnabled = self.memory_table.isSortingEnabled()
        self.memory_table.setSortingEnabled(False)
        self.memory_table.setSortingEnabled(__sortingEnabled)
        self.coding_label.setText(_translate("main_window", "Code"))
        self.input_label.setText(_translate("main_window", "Input"))
        self.console_label.setText(_translate("main_window", "Console"))
        self.microoperation_label.setText(
            _translate("main_window", "Micro Operation"))
        self.SC_value_label.setText(_translate("main_window", "0"))
        self.SC_label.setText(_translate("main_window", "SC"))
        self.PC_value_label.setText(_translate("main_window", "000"))
        self.PC_label.setText(_translate("main_window", "PC"))
        self.AR_value_label.setText(_translate("main_window", "000"))
        self.AR_label.setText(_translate("main_window", "AR"))
        self.IR_value_label.setText(_translate("main_window", "0000"))
        self.IR_label.setText(_translate("main_window", "IR"))
        self.DR_value_label.setText(_translate("main_window", "0000"))
        self.DR_label.setText(_translate("main_window", "DR"))
        self.AC_value_label.setText(_translate("main_window", "0000"))
        self.AC_label.setText(_translate("main_window", "AC"))
        self.TR_label.setText(_translate("main_window", "TR"))
        self.INPR_label.setText(_translate("main_window", "INPR"))
        self.OUTR_label.setText(_translate("main_window", "OUTR"))
        self.I_label.setText(_translate("main_window", "I"))
        self.S_label.setText(_translate("main_window", "S"))
        self.E_label.setText(_translate("main_window", "E"))
        self.R_label.setText(_translate("main_window", "R"))
        self.IEN_label.setText(_translate("main_window", "IEN"))
        self.FGI_label.setText(_translate("main_window", "FGI"))
        self.FGO_label.setText(_translate("main_window", "FGO"))
        self.TR_value_label.setText(_translate("main_window", "0000"))
        self.INPR_value_label.setText(_translate("main_window", "00"))
        self.OUTR_value_label.setText(_translate("main_window", "00"))
        self.INST_label.setText(_translate("main_window", "INST"))
        self.INST_value_label.setText(_translate("main_window", "00"))

    def operations(self):
        arguments = [self.console, self.coding_text, self.microoperation, self.memory_table, self.SC_value_label, self.PC_value_label, self.AR_value_label,
                     self.IR_value_label, self.DR_value_label, self.AC_value_label, self.TR_value_label, self.INPR_value_label, self.OUTR_value_label,
                     self.INST_value_label, self.I_value, self.S_value, self.E_value, self.R_value, self.IEN_value, self.FGI_value, self.FGO_value, self.input]
        self.code_button.clicked.connect(
            lambda: signals.beautify_code(self.coding_text))
        self.compile_button.clicked.connect(
            lambda: signals.compile_code(*arguments))
        self.next_button.clicked.connect(
            lambda: signals.next_step(*arguments))
        self.run_button.clicked.connect(lambda: signals.run(*arguments))
        self.stop_button.clicked.connect(lambda: signals.reset(*arguments))
        self.save_button.clicked.connect(
            lambda: signals.save_code(self.coding_text))
        self.open_button.clicked.connect(
            lambda: signals.open_code(self.coding_text))
        self.goto_information.clicked.connect(
            lambda: self.info())
        self.input.textChanged.connect(
            lambda: signals.text_changed(self.input))

    def info(self):
        self.dialog.show()


class Ui_information_window(object):
    def setupUi(self, information_window):
        information_window.setObjectName("information_window")
        information_window.resize(1390, 800)
        self.about_project_text = QtWidgets.QPlainTextEdit(information_window)
        self.about_project_text.setGeometry(QtCore.QRect(310, 290, 781, 91))
        self.about_project_text.setStyleSheet("background: #0000ffff;\n"
                                              "color: #afc5d0;\n"
                                              "font: 75 10.5pt \"MS Shell Dlg 2\";\n"
                                              "")
        self.about_project_text.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.about_project_text.setReadOnly(True)
        self.about_project_text.setObjectName("about_project_text")
        self.computer_label = QtWidgets.QLabel(information_window)
        self.computer_label.setGeometry(QtCore.QRect(260, 230, 61, 51))
        self.computer_label.setStyleSheet("background: #0000ffff;\n"
                                          "background-image: url(:/images/images/copmuter.png);\n"
                                          "background-repeat: no-repeat;")
        self.computer_label.setText("")
        self.computer_label.setObjectName("computer_label")
        self.team_label = QtWidgets.QLabel(information_window)
        self.team_label.setGeometry(QtCore.QRect(270, 420, 61, 51))
        self.team_label.setStyleSheet("background: #0000ffff;\n"
                                      "background-repeat: no-repeat;\n"
                                      "background-image: url(:/images/images/team.png);")
        self.team_label.setText("")
        self.team_label.setObjectName("team_label")
        self.github_icon_1 = QtWidgets.QLabel(information_window)
        self.github_icon_1.setGeometry(QtCore.QRect(310, 490, 41, 41))
        self.github_icon_1.setStyleSheet("background: #0000ffff;\n"
                                         "background-repeat: no-repeat;\n"
                                         "background-image: url(:/images/images/github.png);")
        self.github_icon_1.setText("")
        self.github_icon_1.setObjectName("github_icon_1")
        self.github_icon_2 = QtWidgets.QLabel(information_window)
        self.github_icon_2.setGeometry(QtCore.QRect(610, 490, 41, 41))
        self.github_icon_2.setStyleSheet("background: #0000ffff;\n"
                                         "background-image: url(:/images/images/github.png);\n"
                                         "background-repeat: no-repeat;")
        self.github_icon_2.setText("")
        self.github_icon_2.setObjectName("github_icon_2")
        self.github_icon_3 = QtWidgets.QLabel(information_window)
        self.github_icon_3.setGeometry(QtCore.QRect(860, 490, 41, 41))
        self.github_icon_3.setStyleSheet("background: #0000ffff;\n"
                                         "background-repeat: no-repeat;\n"
                                         "background-image: url(:/images/images/github.png);")
        self.github_icon_3.setText("")
        self.github_icon_3.setObjectName("github_icon_3")
        self.name_2 = QtWidgets.QPlainTextEdit(information_window)
        self.name_2.setGeometry(QtCore.QRect(650, 490, 181, 71))
        self.name_2.setStyleSheet("background: #0000ffff;\n"
                                  "color: #afc5d0;\n"
                                  "font: 75 9.5pt \"MS Shell Dlg 2\";\n"
                                  "")
        self.name_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.name_2.setReadOnly(True)
        self.name_2.setObjectName("name_2")
        self.name_1 = QtWidgets.QPlainTextEdit(information_window)
        self.name_1.setGeometry(QtCore.QRect(350, 490, 171, 81))
        self.name_1.setStyleSheet("background: #0000ffff;\n"
                                  "color: #afc5d0;\n"
                                  "font: 75 9.5pt \"MS Shell Dlg 2\";\n"
                                  "")
        self.name_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.name_1.setReadOnly(True)
        self.name_1.setObjectName("name_1")
        self.name_3 = QtWidgets.QPlainTextEdit(information_window)
        self.name_3.setGeometry(QtCore.QRect(900, 490, 211, 71))
        self.name_3.setStyleSheet("background: #0000ffff;\n"
                                  "color: #afc5d0;\n"
                                  "font: 75 9.5pt \"MS Shell Dlg 2\";\n"
                                  "")
        self.name_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.name_3.setReadOnly(True)
        self.name_3.setObjectName("name_3")
        self.pic = QtWidgets.QLabel(information_window)
        self.pic.setGeometry(QtCore.QRect(0, 0, 1390, 800))
        self.pic.setText("")
        self.pic.setPixmap(QtGui.QPixmap(":/images/images/back1.png"))
        self.pic.setScaledContents(True)
        self.pic.setObjectName("pic")
        self.pic.raise_()
        self.about_project_text.raise_()
        self.computer_label.raise_()
        self.team_label.raise_()
        self.github_icon_1.raise_()
        self.github_icon_2.raise_()
        self.github_icon_3.raise_()
        self.name_2.raise_()
        self.name_1.raise_()
        self.name_3.raise_()

        self.retranslateUi(information_window)
        QtCore.QMetaObject.connectSlotsByName(information_window)

    def retranslateUi(self, information_window):
        _translate = QtCore.QCoreApplication.translate
        information_window.setWindowTitle(
            _translate("information_window", "Information"))
        self.about_project_text.setPlainText(_translate(
            "information_window", "This is a Qt & Python application that compiles assembly code and runs a simulation of Mano\'s Computer as detailed in: Computer System Architecture, 3rd edition by M. Morris Mano Published by Prentice-Hall, c 1993 Chapter 5, pp 123-172."))
        self.name_2.setPlainText(_translate("information_window", "Melika Fotoohi\n"
                                            "MelikaFotoohi"))
        self.name_1.setPlainText(_translate("information_window", "Mohammad Nasajpour\n"
                                            "mhnasajpour"))
        self.name_3.setPlainText(_translate("information_window", "Fatemeh Ghadamzadeh\n"
                                            "ftmh.ghz"))


class Info(QtWidgets.QWidget):
    def __init__(self, parent=None):
        super(Info, self).__init__(parent)
        self.ui = Ui_information_window()
        self.ui.setupUi(self)


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    main_window = QtWidgets.QWidget()
    ui = Ui_main_window()
    ui.setupUi(main_window)
    ui.operations()
    main_window.show()
    sys.exit(app.exec_())
